"""Package recorded engine comparisons as an artifact bundle."""
import base64, json, statistics, sys
from pathlib import Path
root=Path(sys.argv[1]);out=Path(sys.argv[2]);out.mkdir(exist_ok=True)
reports={engine:json.loads((root/(engine+'-results.json')).read_text()) for engine in ['raven','pocket']}
cases=[('alba','prose','Alba · prose'),('marius','prose','Marius · prose'),('alba','mixed','Alba · numbers & abbreviations')]
files={};samples=[]
for voice,case,label in cases:
 row={'label':label}
 for engine in reports:
  name=f'{engine}-{voice}-{case}-0';audio='data:audio/flac;base64,'+base64.b64encode((root/(name+'.flac')).read_bytes()).decode()
  files[name+'.js']='window.trialAudio['+json.dumps(name)+']='+json.dumps(audio)+';'
  selected=[r for r in reports[engine]['runs'] if r['voice']==voice and r['case']==case and r['repeat'] in (0,1,2)]
  row[engine]={'name':name,'first':round(statistics.median(r['first_audio_seconds'] for r in selected)*1000),'generation':round(statistics.median(r['generation_seconds'] for r in selected),2),'realtime':round(statistics.median(r['realtime_multiple'] for r in selected),1)}
 samples.append(row)
for name in ['default','low-latency','low-latency-trim']:
 key='raven-cli-'+name
 files[key+'.js']='window.trialAudio['+json.dumps(key)+']='+json.dumps('data:audio/flac;base64,'+base64.b64encode((root/(key+'.flac')).read_bytes()).decode())+';'
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pocket experiments · RAVEN</title><style>
:root{color-scheme:light;--ink:#243b32;--muted:#606c64;--paper:#f7f5ed;--line:#c9d0bf}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.6 system-ui,sans-serif}main{max-width:930px;margin:6vh auto;padding:0 24px 60px}.eyebrow{font-size:12px;letter-spacing:.14em;text-transform:uppercase;color:var(--muted)}h1{font:normal clamp(36px,6vw,56px)/1.15 Georgia,serif;margin:18px 0}h2{font:normal 26px Georgia,serif}p{color:var(--muted)}.controls{display:flex;flex-wrap:wrap;gap:20px;margin:30px 0 24px}label{display:grid;gap:6px;font-size:13px}select{min-height:46px;max-width:100%;font:inherit;color:inherit;background:transparent;border:1px solid #9aa891;border-radius:6px;padding:10px}.comparison{display:grid;grid-template-columns:1fr 1fr;border-block:1px solid var(--line)}.engine{padding:24px 24px 24px 0}.engine+ .engine{border-left:1px solid var(--line);padding-left:24px;padding-right:0}.engine h2{margin:6px 0 18px}.tag{font-size:12px;color:var(--muted)}audio{display:block;width:100%;margin:16px 0}.metric{font-size:13px}.metric strong{color:var(--ink)}#passage{font:21px/1.75 Georgia,serif;color:var(--ink);margin:25px 0}details{border-block:1px solid var(--line);padding:20px 0}summary{cursor:pointer;font-size:17px}footer{font-size:13px;color:var(--muted);margin-top:24px}a{color:inherit}:focus-visible{outline:2px solid #5e7233;outline-offset:4px}@media(max-width:600px){main{margin-top:30px;padding-inline:20px}.comparison{grid-template-columns:1fr}.engine,.engine+ .engine{padding:20px 0;border-left:0}.engine+ .engine{border-top:1px solid var(--line)}.controls{display:grid}select{width:100%}}
</style><main><div class="eyebrow">Pocket experiments / 02</div><h1>Listen to RAVEN.</h1><p>Compare the new native runtime with our current Pocket reader. Both use int8 on CPU, preset voices, and a temperature of 0.3.</p><div class="controls"><label>Passage<select id="sample"><option value="0">Alba · prose</option><option value="1">Marius · prose</option><option value="2">Alba · numbers & abbreviations</option></select></label><label>Playback speed<select id="rate"><option value="1">1×</option><option value="1.25">1.25×</option><option value="1.5">1.5×</option></select></label></div><div class="comparison"><section class="engine"><span class="tag">Current reader engine</span><h2>Pocket + timestamps</h2><audio id="pocket" controls preload="metadata"></audio><div id="pocket-metric" class="metric"></div></section><section class="engine"><span class="tag">Isolated trial · no word timestamps</span><h2>RAVEN</h2><audio id="raven" controls preload="metadata"></audio><div id="raven-metric" class="metric"></div></section></div><p id="passage"></p><details><summary>Explore RAVEN's startup settings</summary><p>These Alba samples compare the standard startup gate with low latency, with and without leading-audio trimming. Listen for the opening word, blips, and any clipped onset.</p><label>Startup setting<select id="variant"><option value="default">Default gate</option><option value="low-latency">Low latency · gate off</option><option value="low-latency-trim">Low latency · gate retained</option></select></label><audio id="startup" controls preload="metadata"></audio><p class="metric">These variants were recorded through the command-line program. Process startup and model loading make their timings unsuitable for comparison with the resident-engine measurements above.</p></details><footer>These are prerecorded samples; the players do not reproduce generation delay. Metrics are medians of three warm runs on VM310 under the same two-CPU quota. Different runtimes and voice conditioning can change speech duration and loudness; samples have not been loudness-normalized. RAVEN uses the official preset reference recordings, while Pocket uses its preset states. The production reader is unchanged by this trial.<br><a href="https://github.com/pkalogiros/pocket-tts-raven">RAVEN source</a></footer></main><script>window.trialAudio={};</script>__SCRIPTS__<script>
const samples=__SAMPLES__,text=__TEXTS__;
const audios=[...document.querySelectorAll('audio')],sample=document.getElementById('sample'),rate=document.getElementById('rate'),variant=document.getElementById('variant');
for(const audio of audios){audio.addEventListener('play',()=>audios.forEach(other=>{if(other!==audio)other.pause()}));audio.preservesPitch=true}
function load(){audios.forEach(a=>a.pause());const item=samples[+sample.value];for(const engine of ['pocket','raven']){const audio=document.getElementById(engine),m=item[engine];audio.src=trialAudio[m.name];audio.playbackRate=+rate.value;document.getElementById(engine+'-metric').textContent=m.first+' ms to first audio · '+m.generation+' s generation · '+m.realtime+'× real time';}document.getElementById('passage').textContent=text[+sample.value];}
function startup(){document.getElementById('startup').src=trialAudio['raven-cli-'+variant.value];document.getElementById('startup').playbackRate=+rate.value}
sample.onchange=load;variant.onchange=startup;rate.onchange=()=>audios.forEach(a=>a.playbackRate=+rate.value);load();startup();
</script></html>'''
texts=['The library was quiet. Beyond the window, rain traced silver lines across the glass. She opened the book and began to read, slowly at first, then with growing confidence.']*2+['The report lists three priorities: reduce waiting time, improve navigation, and preserve reading progress. Revenue rose 12.5%, reaching $1,240. Dr. Evans reviewed the API results on September 12, 2026.']
page=page.replace('__SCRIPTS__',''.join('<script src="'+name+'"></script>' for name in files)).replace('__SAMPLES__',json.dumps(samples)).replace('__TEXTS__',json.dumps(texts))
files['index.html']=page
for name,value in files.items():(out/name).write_text(value)
(out.parent/'raven-bundle.json').write_text(json.dumps(files))
print(json.dumps({'files':len(files),'bytes':sum(len(v.encode()) for v in files.values()),'max_file':max(len(v.encode()) for v in files.values())}))
