"""Build a sentence-navigation interaction trial from existing Pocket timing clips."""
import base64,json,sys
from pathlib import Path
root=Path(sys.argv[1]);runs=json.loads((root/'results.json').read_text())['runs'];samples=[]
for name in ['timestamped-int8-alba-prose','timestamped-int8-marius-prose','timestamped-int8-alba-mixed']:
 r=next(x for x in runs if x['name']==name)
 samples.append({'text':r['text'],'words':[e for e in r['events'] if e['type']=='WordEnd'],'audio':'data:audio/flac;base64,'+base64.b64encode((root/(name+'.flac')).read_bytes()).decode()})
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pocket sentence navigation</title><style>
*{box-sizing:border-box}body{margin:0;background:#f7f5ed;color:#243b32;font:16px/1.6 system-ui,sans-serif}main{max-width:820px;margin:6vh auto;padding:0 24px 50px}h1{font:normal clamp(34px,6vw,50px)/1.15 Georgia,serif}small,footer{color:#606c64;font-size:13px}.settings,.transport{display:flex;flex-wrap:wrap;gap:12px;margin:20px 0}label{display:grid;gap:5px;font-size:13px}select,button{font:inherit;color:inherit;background:transparent;border:1px solid #9aa891;border-radius:6px;padding:10px 14px;min-height:44px}button{cursor:pointer}button:disabled{opacity:.4;cursor:default}#play{background:#243b32;color:#fff}#passage{font:23px/1.9 Georgia,serif;border-block:1px solid #c9d0bf;padding:24px 0}.sentence{border-radius:3px}.sentence.current{background:#e8e5d5}.word.active{background:#dceba6;box-shadow:0 0 0 2px #dceba6}#position{font-size:13px;min-height:24px}:focus-visible{outline:2px solid #526529;outline-offset:4px}footer{margin-top:24px}a{color:inherit}@media(max-width:500px){main{margin-top:30px;padding-inline:20px}.settings{display:grid}#passage{font-size:21px}.transport button{flex:1 1 40%}}
</style><main><small>Pocket experiments / 03</small><h1>Move one sentence at a time.</h1><p>Try replaying a sentence or skipping ahead while Pocket reads. This explores FrontPocket's navigation ideas using our existing Pocket voices and word timings.</p><div class="settings"><label>Sample<select id="sample"><option value="0">Alba · prose</option><option value="1">Marius · prose</option><option value="2">Alba · numbers & abbreviations</option></select></label><label>Speed<select id="rate"><option value="1">1×</option><option value="1.25">1.25×</option><option value="1.5">1.5×</option><option value="2">2×</option></select></label></div><div class="transport" role="group" aria-label="Sentence playback"><button id="previous">Previous sentence</button><button id="replay">Replay sentence</button><button id="play">Play</button><button id="next">Next sentence</button></div><p id="position" role="status"></p><div id="passage"></div><footer>Prerecorded audio, held in this page for immediate navigation. This tests the interaction, not live generation latency or FrontPocket's software. No changes to the native Listen player.<br><a href="https://github.com/markd89/FrontPocket">FrontPocket source</a></footer><audio id="audio" preload="auto"></audio></main><script>
const samples=__SAMPLES__,audio=document.getElementById('audio'),sample=document.getElementById('sample'),rate=document.getElementById('rate'),passage=document.getElementById('passage'),position=document.getElementById('position'),play=document.getElementById('play');
let sentences=[],words=[],current=0,raf=0;
function paint(){const t=audio.currentTime;current=Math.max(0,sentences.findLastIndex(s=>t>=s.start));sentences.forEach((s,i)=>s.node.classList.toggle('current',i===current));words.forEach(w=>w.node.classList.toggle('active',t>=w.start&&t<w.end));position.textContent='Sentence '+(current+1)+' of '+sentences.length;document.getElementById('previous').disabled=current===0;document.getElementById('next').disabled=current===sentences.length-1;play.textContent=audio.paused?'Play':'Pause';}
function tick(){paint();if(!audio.paused)raf=requestAnimationFrame(tick)}
function jump(index){audio.currentTime=sentences[Math.max(0,Math.min(index,sentences.length-1))].start;paint();audio.play().catch(()=>position.textContent='Press Play to begin.');}
function load(){audio.pause();const s=samples[+sample.value];sentences=[];words=[];passage.replaceChildren();let cursor=0;const mapped=s.words.map(w=>{const at=s.text.indexOf(w.word,cursor);if(at<0)throw Error('Word mapping failed');cursor=at+w.word.length;return {...w,offset:at}});
for(const part of new Intl.Segmenter('en',{granularity:'sentence'}).segment(s.text)){const members=mapped.filter(w=>w.offset>=part.index&&w.offset<part.index+part.segment.length);if(!members.length)continue;const span=document.createElement('span');span.className='sentence';let at=part.index;for(const w of members){span.append(document.createTextNode(s.text.slice(at,w.offset)));const node=document.createElement('span');node.className='word';node.textContent=w.word;span.append(node);words.push({...w,node});at=w.offset+w.word.length;}span.append(document.createTextNode(s.text.slice(at,part.index+part.segment.length)));passage.append(span);sentences.push({start:members[0].start,node:span});}audio.src=s.audio;audio.preservesPitch=true;audio.playbackRate=+rate.value;current=0;paint();}
play.onclick=()=>audio.paused?audio.play():audio.pause();document.getElementById('previous').onclick=()=>jump(current-1);document.getElementById('replay').onclick=()=>jump(current);document.getElementById('next').onclick=()=>jump(current+1);sample.onchange=load;rate.onchange=()=>audio.playbackRate=+rate.value;audio.onplay=()=>{cancelAnimationFrame(raf);tick()};audio.onpause=()=>{cancelAnimationFrame(raf);paint()};audio.onseeked=paint;audio.onended=paint;load();
</script></html>'''
Path(sys.argv[2]).write_text(html.replace('__SAMPLES__',json.dumps(samples).replace('</','<\\/')))
