// SPDX-License-Identifier: Apache-2.0
// SQLite durability contract only; a future worker owns all provider HTTP.
import crypto from "node:crypto";
export const MAX_OUTBOX_PAYLOAD_BYTES = 32 * 1024;
export const MAX_OUTBOX_GLOBAL = 10_000;
export const MAX_OUTBOX_TENANT = 1_000;
export const OUTBOX_LEASE_MS = 30_000;
export const OUTBOX_MAX_ATTEMPTS = 8;
export const MAX_OUTBOX_TARGET_KEY_BYTES = 160;
export const MAX_OUTBOX_SECRET_REF_BYTES = 128;
export const MAX_OUTBOX_BUCKET_KEY_BYTES = 128;
const hash = (payload) => crypto.createHash("sha256").update(payload).digest("hex");
const valid = (value) => typeof value === "string" && value.trim() && !value.includes("\0");
const SAFE_TERMINAL_CODES = new Set(["invalid_webhook", "unknown_webhook", "invalid_secret", "decrypt_failed", "allowlist_rejected", "redirect", "bad_request", "unauthorized", "forbidden", "not_found", "invalid_rate_limit_delay", "client_error", "contract_error", "payload_hash_mismatch", "permission_denied", "validation_failed", "provider_unavailable", "attempts_exhausted"]);
const SAFE_RETRY_CLASSIFICATIONS = new Set(["retry", "network_retry", "ambiguous_worker_restart", "provider_unavailable", "rate_limited", "network", "timeout", "ambiguous", "server_error"]);
const SAFE_TERMINAL_CLASSIFICATIONS = new Set(["attempts_exhausted", "attempts_exhausted_after_worker_restart", "invalid_webhook", "unknown_webhook", "permission_denied", "validation_failed", "provider_unavailable", "dead_letter", "server_error", "invalid_secret", "decrypt_failed", "allowlist_rejected", "redirect", "bad_request", "unauthorized", "forbidden", "not_found", "invalid_rate_limit_delay", "client_error", "contract_error", "payload_hash_mismatch"]);
const redact = (error) => SAFE_TERMINAL_CODES.has(String(error || "")) ? String(error) : "provider delivery failed";
const opaqueTargetKey = (value) => typeof value === "string" && value.length > 0 && value.length <= MAX_OUTBOX_TARGET_KEY_BYTES && /^[A-Za-z0-9_.-]+$/.test(value);
const opaqueSecretRef = (value) => typeof value === "string" && value.length <= MAX_OUTBOX_SECRET_REF_BYTES && /^webhook:[A-Za-z0-9_.-]+$/.test(value);
const opaqueBucketKey = (value) => typeof value === "string" && value.length > 0 && value.length <= MAX_OUTBOX_BUCKET_KEY_BYTES && !/[\0\r\n]/.test(value) && !/^https?:\/\//i.test(value) && !/\/api\/webhooks\//i.test(value);
function publicRow(row) { if (!row) return undefined; const { secret_ref, payload, lease_token, ...safe } = row; return { ...safe, payload_bytes: Buffer.byteLength(payload) }; }

export function createOutboxStore({ db, now = () => Date.now(), id = () => crypto.randomUUID() } = {}) {
  if (!db) throw new TypeError("db is required");
  const allColumns = "id,event_id,tenant,event_type,target_key,bucket_id,secret_ref,payload,payload_sha256,durability_intent_id,state,attempts,next_attempt_at,lease_owner,lease_expires_at,lease_token,lease_version,result_classification,duplicate_risk,discord_message_id,terminal_error,created_at,updated_at,completed_at";
  const get = db.prepare(`SELECT ${allColumns} FROM provider_delivery_outbox WHERE id=?`);
  const prior = db.prepare(`SELECT ${allColumns} FROM provider_delivery_outbox WHERE provider='discord' AND tenant=@tenant AND target_key=@target_key AND event_id=@event_id`);
  const active = db.prepare("SELECT COUNT(*) count FROM provider_delivery_outbox WHERE state IN ('blocked','ready','leased','retry')");
  const tenantActive = db.prepare("SELECT COUNT(*) count FROM provider_delivery_outbox WHERE tenant=? AND state IN ('blocked','ready','leased','retry')");
  const insert = db.prepare(`INSERT INTO provider_delivery_outbox (id,provider,event_id,tenant,event_type,target_key,bucket_id,secret_ref,payload,payload_sha256,durability_intent_id,state,next_attempt_at,created_at,updated_at) VALUES (@id,'discord',@event_id,@tenant,@event_type,@target_key,@target_key,@secret_ref,@payload,@payload_sha256,@durability_intent_id,@state,@now,@now,@now)`);
  const releaseIntent = db.prepare("UPDATE provider_delivery_outbox SET state='ready', durability_intent_id=NULL, updated_at=? WHERE durability_intent_id=? AND state='blocked'");
  const deleteBlocked = db.prepare("DELETE FROM provider_delivery_outbox WHERE durability_intent_id=? AND state='blocked'");
  const deleteIntent = db.prepare("DELETE FROM artifact_durability_intents WHERE id=?");
  function normalize(input = {}) { const payload = Buffer.isBuffer(input.payload) ? input.payload : Buffer.from(String(input.payload ?? "")); const row = { event_id:String(input.event_id || ""),tenant:String(input.tenant || ""),event_type:String(input.event_type || ""),target_key:String(input.target_key || ""),secret_ref:String(input.secret_ref || ""),payload,durability_intent_id:input.durability_intent_id == null ? null : String(input.durability_intent_id),now:Number(now()) }; if (payload.length > MAX_OUTBOX_PAYLOAD_BYTES) throw new RangeError("outbox payload exceeds 32 KiB"); if (![row.event_id,row.tenant,row.event_type,row.target_key,row.secret_ref].every(valid) || !opaqueTargetKey(row.target_key) || !opaqueSecretRef(row.secret_ref)) throw new TypeError("outbox identity fields are required"); if (!Number.isSafeInteger(row.now) || row.now < 0) throw new TypeError("clock must return epoch milliseconds"); row.payload_sha256=hash(payload); if (input.payload_sha256 != null && String(input.payload_sha256) !== row.payload_sha256) throw new Error("payload hash does not match payload"); row.state=row.durability_intent_id ? "blocked" : "ready"; return row; }
  // Producers invoke this inside their mutation transaction. All fanout checks happen before any INSERT.
  function enqueueManyInTransaction(inputs) { const rows = inputs.map(normalize); const result=[]; const fresh=[]; for (const row of rows) { const old=prior.get(row); if (old) { if (old.payload_sha256 !== row.payload_sha256 || old.event_type !== row.event_type || old.secret_ref !== row.secret_ref || old.durability_intent_id !== row.durability_intent_id) throw new Error("outbox idempotency conflict"); result.push(publicRow(old)); } else fresh.push(row); } if (active.get().count + fresh.length > MAX_OUTBOX_GLOBAL) throw new Error("outbox capacity exceeded"); for (const tenant of new Set(fresh.map((row) => row.tenant))) if (tenantActive.get(tenant).count + fresh.filter((row) => row.tenant === tenant).length > MAX_OUTBOX_TENANT) throw new Error("outbox tenant capacity exceeded"); for (const row of fresh) { row.id=String(id()); if (!valid(row.id)) throw new TypeError("outbox id is required"); insert.run(row); result.push(publicRow(get.get(row.id))); } return result; }
  const enqueueMany = db.transaction(enqueueManyInTransaction).immediate;
  const enqueue = (input) => enqueueMany([input])[0];
  const recover = db.prepare(`UPDATE provider_delivery_outbox SET state=CASE WHEN attempts >= @max THEN 'dead_letter' ELSE 'retry' END, lease_owner=NULL,lease_expires_at=NULL,lease_token=NULL,result_classification=CASE WHEN attempts >= @max THEN 'attempts_exhausted_after_worker_restart' ELSE 'ambiguous_worker_restart' END,duplicate_risk=1,terminal_error=CASE WHEN attempts >= @max THEN 'delivery attempts exhausted after worker restart' ELSE '' END,next_attempt_at=@now,updated_at=@now,completed_at=CASE WHEN attempts >= @max THEN @now ELSE NULL END WHERE state='leased' AND lease_expires_at <= @now`);
  const candidate = db.prepare(`SELECT o.id FROM provider_delivery_outbox o WHERE o.state IN ('ready','retry') AND o.durability_intent_id IS NULL AND o.attempts < @max AND o.next_attempt_at <= @now AND NOT EXISTS (SELECT 1 FROM provider_delivery_rate_limits r WHERE r.provider=o.provider AND r.blocked_until > @now AND (r.scope='global' OR (r.scope='target' AND r.target_key=o.target_key) OR (r.scope='bucket' AND r.bucket_id=o.bucket_id AND r.top_level_secret_ref=o.secret_ref))) AND NOT EXISTS (SELECT 1 FROM provider_delivery_outbox earlier WHERE earlier.target_key=o.target_key AND earlier.state IN ('blocked','ready','leased','retry') AND (earlier.created_at < o.created_at OR (earlier.created_at=o.created_at AND earlier.id < o.id))) AND NOT EXISTS (SELECT 1 FROM provider_delivery_outbox active WHERE active.state='leased' AND active.lease_expires_at > @now AND (active.target_key=o.target_key OR (active.bucket_id=o.bucket_id AND active.secret_ref=o.secret_ref))) ORDER BY o.created_at,o.id LIMIT 1`);
  const lease = db.prepare(`UPDATE provider_delivery_outbox SET state='leased',attempts=attempts+1,lease_owner=@worker,lease_expires_at=@expires,lease_token=@token,lease_version=lease_version+1,updated_at=@now WHERE id=@id AND state IN ('ready','retry') AND durability_intent_id IS NULL`);
  const claimNext = db.transaction((worker) => { worker=String(worker || ""); const token=String(id()); if (!valid(worker) || !valid(token)) throw new TypeError("worker and lease token are required"); const timestamp=Number(now()); recover.run({ now:timestamp,max:OUTBOX_MAX_ATTEMPTS }); const picked=candidate.get({now:timestamp,max:OUTBOX_MAX_ATTEMPTS}); if (!picked) return undefined; if (lease.run({id:picked.id,worker,token,now:timestamp,expires:timestamp+OUTBOX_LEASE_MS}).changes !== 1) throw new Error("outbox claim conflict"); return get.get(picked.id); }).immediate;
  const transition = db.prepare(`UPDATE provider_delivery_outbox SET state=@state,lease_owner=NULL,lease_expires_at=NULL,lease_token=NULL,next_attempt_at=@next,result_classification=@classification,duplicate_risk=@duplicate_risk,discord_message_id=CASE WHEN @state='accepted' THEN @message ELSE discord_message_id END,terminal_error=@error,updated_at=@now,completed_at=CASE WHEN @state IN ('accepted','dead_letter') THEN @now ELSE NULL END WHERE id=@id AND state='leased' AND lease_owner=@worker AND lease_token=@token AND lease_version=@lease_version AND (@requires_exhaustion=0 OR attempts >= @max)`);
  const retryTransition = db.prepare(`UPDATE provider_delivery_outbox SET state=CASE WHEN attempts >= @max THEN 'dead_letter' ELSE 'retry' END,lease_owner=NULL,lease_expires_at=NULL,lease_token=NULL,next_attempt_at=CASE WHEN attempts >= @max THEN @now ELSE @next END,result_classification=CASE WHEN attempts >= @max THEN 'attempts_exhausted' ELSE @classification END,duplicate_risk=@duplicate_risk,terminal_error=CASE WHEN attempts >= @max THEN 'attempts_exhausted' ELSE '' END,updated_at=@now,completed_at=CASE WHEN attempts >= @max THEN @now ELSE NULL END WHERE id=@id AND state='leased' AND lease_owner=@worker AND lease_token=@token AND lease_version=@lease_version`);
  function finish(idValue, worker, token, leaseVersion, state, { next = Number(now()), classification = state, message = "", error = "", duplicateRisk = false, requiresExhaustion = false } = {}) { const timestamp=Number(now()); return transition.run({id:String(idValue||""),worker:String(worker||""),token:String(token||""),lease_version:Number(leaseVersion),state,next:Number(next),classification:String(classification||""),message:String(message||""),error:redact(error),duplicate_risk:duplicateRisk?1:0,requires_exhaustion:requiresExhaustion?1:0,max:OUTBOX_MAX_ATTEMPTS,now:timestamp}).changes === 1; }
  function retryDelivery(idValue, worker, token, leaseVersion, next, classification = "retry", duplicateRisk = false) { classification=String(classification||""); if (!SAFE_RETRY_CLASSIFICATIONS.has(classification)) throw new TypeError("invalid outbox result classification"); return retryTransition.run({id:String(idValue||""),worker:String(worker||""),token:String(token||""),lease_version:Number(leaseVersion),next:Number(next),classification,duplicate_risk:duplicateRisk?1:0,now:Number(now()),max:OUTBOX_MAX_ATTEMPTS}).changes === 1; }
  function deadLetter(idValue, worker, token, leaseVersion, classification, error, duplicateRisk = false) { classification=String(classification||""); if (!SAFE_TERMINAL_CLASSIFICATIONS.has(classification)) throw new TypeError("invalid outbox result classification"); if (duplicateRisk && classification !== "attempts_exhausted") throw new TypeError("duplicate risk is valid only for exhausted delivery"); return finish(idValue,worker,token,leaseVersion,"dead_letter",{classification,error,duplicateRisk,requiresExhaustion:classification.startsWith("attempts_exhausted")}); }
  function persistRateLimit({ scope, target_key = "", bucket_id = "", top_level_secret_ref = "", blocked_until }) {
    scope=String(scope||""); target_key=String(target_key||""); bucket_id=String(bucket_id||""); top_level_secret_ref=String(top_level_secret_ref||"");
    const timestamp=Number(now());
    const validScope = (scope === "global" && !target_key && !bucket_id && !top_level_secret_ref)
      || (scope === "target" && opaqueTargetKey(target_key) && !bucket_id && !top_level_secret_ref)
      || (scope === "bucket" && opaqueTargetKey(target_key) && opaqueBucketKey(bucket_id) && opaqueSecretRef(top_level_secret_ref));
    if (!validScope || !Number.isSafeInteger(blocked_until) || blocked_until < 0) throw new TypeError("invalid rate limit state");
    const storedTarget = scope === "target" ? target_key : "";
    const storedBucket = scope === "bucket" ? bucket_id : "";
    const storedSecret = scope === "bucket" ? top_level_secret_ref : "";
    db.transaction(() => {
      db.prepare(`INSERT INTO provider_delivery_rate_limits (provider,scope,target_key,bucket_id,top_level_secret_ref,blocked_until,updated_at) VALUES ('discord',?,?,?,?,?,?) ON CONFLICT(provider,scope,target_key,bucket_id,top_level_secret_ref) DO UPDATE SET blocked_until=MAX(provider_delivery_rate_limits.blocked_until,excluded.blocked_until),updated_at=CASE WHEN excluded.blocked_until >= provider_delivery_rate_limits.blocked_until THEN excluded.updated_at ELSE provider_delivery_rate_limits.updated_at END`).run(scope,storedTarget,storedBucket,storedSecret,blocked_until,timestamp);
      if (scope === "bucket") db.prepare("UPDATE provider_delivery_outbox SET bucket_id=?, updated_at=? WHERE target_key=? AND secret_ref=? AND state IN ('blocked','ready','retry')").run(bucket_id,timestamp,target_key,top_level_secret_ref);
    })();
  }
  function finalizeDurabilitySuccessInTransaction(intent) { const changed=releaseIntent.run(Number(now()),String(intent||"")).changes; deleteIntent.run(String(intent||"")); return changed; }
  function compensateDurabilityInTransaction(intent) { const changed=deleteBlocked.run(String(intent||"")).changes; deleteIntent.run(String(intent||"")); return changed; }
  return { enqueue, enqueueMany, enqueueInTransaction:(input) => enqueueManyInTransaction([input])[0], enqueueManyInTransaction, finalizeDurabilitySuccessInTransaction, compensateDurabilityInTransaction, claimNext, persistRateLimit, applyRateLimit:persistRateLimit, accepted:(idValue,worker,token,leaseVersion,message) => finish(idValue,worker,token,leaseVersion,"accepted",{message,classification:"accepted"}), retry:retryDelivery, deadLetter, get:(idValue)=>publicRow(get.get(String(idValue||""))), getDelivery:(idValue)=>get.get(String(idValue||"")), verifyPayloadHash:(record)=>!!record && hash(Buffer.from(record.payload))===record.payload_sha256, depth:()=>Number(active.get().count) };
}
