"""Build a self-contained listening trial from trial.py output."""
import base64
import json
from pathlib import Path
import sys

root = Path(sys.argv[1])
data = json.loads((root / 'results.json').read_text())
names = ['timestamped-int8-alba-prose', 'timestamped-int8-marius-prose', 'timestamped-int8-alba-mixed', 'baseline-int8-alba-prose']
samples = []
for name in names:
    run = next(r for r in data['runs'] if r['name'] == name)
    samples.append({'name': name, 'text': run['text'], 'words': [e for e in run['events'] if e['type'] == 'WordEnd'], 'audio': 'data:audio/flac;base64,' + base64.b64encode((root / (name + '.flac')).read_bytes()).decode()})
html = '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pocket · Word timing trial</title>
<style>
:root{color-scheme:light;--ink:#25392f;--muted:#626c62;--paper:#f7f5ee;--accent:#dceba6}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.6 system-ui,sans-serif}main{max-width:830px;margin:7vh auto;padding:0 26px 60px}.eyebrow{font-size:12px;letter-spacing:.13em;text-transform:uppercase;color:var(--muted)}h1{font:normal clamp(34px,6vw,54px)/1.12 Georgia,serif;margin:20px 0}p{color:var(--muted)}.controls{display:flex;flex-wrap:wrap;gap:18px;margin:30px 0 18px}label{font-size:13px;display:grid;gap:5px}select{font:inherit;color:var(--ink);padding:12px;background:transparent;border:1px solid #aab0a3;border-radius:7px;max-width:100%}audio{width:100%;margin:8px 0 22px}#passage{font:23px/1.9 Georgia,serif;border-block:1px solid #cbd0bf;padding:28px 0;min-height:240px;color:var(--ink)}.word{font:inherit;color:inherit;display:inline;border:0;background:none;padding:2px 0;cursor:pointer;border-radius:3px}.word:hover{box-shadow:0 2px #81904f}.word.active{background:var(--accent);box-shadow:0 0 0 3px var(--accent)}:focus-visible{outline:2px solid #526529;outline-offset:4px}#status{min-height:25px;font-size:13px}footer{font-size:13px;margin-top:25px;color:var(--muted)}a{color:inherit}@media(max-width:500px){main{margin-top:30px;padding-inline:20px}#passage{font-size:21px}.controls{display:grid;grid-template-columns:1fr}select{width:100%}}
</style><main><div class="eyebrow">Pocket experiments / 01</div><h1>Follow the words.</h1><p>A listening trial using real Pocket word timings. Play a sample, change the speed, or click a word to start there.</p><div class="controls"><label>Sample<select id="sample"><option>Alba · prose · timestamps</option><option>Marius · prose · timestamps</option><option>Alba · numbers & abbreviations</option><option>Alba · current engine baseline</option></select></label><label>Playback speed<select id="rate"><option value="0.8">0.8×</option><option value="1" selected>1×</option><option value="1.25">1.25×</option><option value="1.5">1.5×</option><option value="2">2×</option></select></label></div><audio id="audio" controls preload="metadata"></audio><div id="passage"></div><p id="status" role="status"></p><footer>These are prerecorded samples generated on our CPU server with preset voices. Highlighting follows the audio clock; this page does not measure live generation delay. Timing is approximate, especially around numbers and punctuation. The production player is unchanged.<br><a href="https://github.com/dpm63/pocket-tts-timestamped">Pocket TTS Timestamped source</a></footer></main><script>
const samples=__SAMPLES__;
const audio=document.getElementById('audio'),sample=document.getElementById('sample'),rate=document.getElementById('rate'),passage=document.getElementById('passage'),status=document.getElementById('status');
let buttons=[],words=[],active=-1,raf=0;
function paint(){const t=audio.currentTime;const i=words.findIndex(w=>t>=w.start&&t<w.end);if(i!==active){if(buttons[active])buttons[active].classList.remove('active');if(buttons[i])buttons[i].classList.add('active');active=i}}
function tick(){paint();if(!audio.paused&&!audio.ended)raf=requestAnimationFrame(tick)}
function load(){audio.pause();const s=samples[+sample.value||sample.selectedIndex];words=s.words;buttons=[];active=-1;passage.replaceChildren();let cursor=0;for(const w of words){const at=s.text.indexOf(w.word,cursor);if(at<0)throw Error('Word mapping failed: '+w.word);passage.append(document.createTextNode(s.text.slice(cursor,at)));const b=document.createElement('button');b.className='word';b.textContent=w.word;b.setAttribute('aria-label','Read from '+w.word);b.onclick=()=>{audio.currentTime=w.start;paint();audio.play().catch(()=>status.textContent='Use the audio play button to begin.');};buttons.push(b);passage.append(b);cursor=at+w.word.length;}passage.append(document.createTextNode(s.text.slice(cursor)));audio.src=s.audio;audio.playbackRate=+rate.value;audio.preservesPitch=true;status.textContent=words.length?'Click any word to jump to its recorded start time.':'Baseline sample: word timings are not available.';}
sample.onchange=load;rate.onchange=()=>audio.playbackRate=+rate.value;audio.onplay=()=>{cancelAnimationFrame(raf);tick()};audio.onpause=()=>{cancelAnimationFrame(raf);paint()};audio.onseeked=paint;audio.ontimeupdate=paint;audio.onended=()=>{cancelAnimationFrame(raf);paint()};audio.onerror=()=>status.textContent='Audio could not load in this browser.';load();
</script></html>'''
# Option values are deliberately explicit to keep selection independent of labels.
html=html.replace('<option>Alba · prose', '<option value="0">Alba · prose',1).replace('<option>Marius', '<option value="1">Marius',1).replace('<option>Alba · numbers', '<option value="2">Alba · numbers',1).replace('<option>Alba · current', '<option value="3">Alba · current',1)
Path(sys.argv[2]).write_text(html.replace('__SAMPLES__', json.dumps(samples).replace('</','<\\/')))
